server:
  port: 8089

spring:
  application:
    name: greeting-service

greeting-service:
  greeting: Ola
  default-value: Ambiente default

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'


#spring:
#  application:
#    name:
#  config:
#    import: optional:configserver:http://localhost:8888/
#  cloud:
#    config:
#      profile: prod
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - '*'
#greeting-service:
#  greeting: "Olá"
#  default-value: "Mundo"
